DEBT-222 - Resolve dependency conflicts for jackson
Jersey 1.19 depends on jackson 1.9.2.
This made testkit provide jackson-jaxrs:1.9.2 and jackson-xc:1.9.2.
As we bumped testkit in bundled plugins it crashed some tests with java.lang.NoSuchMethodError: org.codehaus.jackson.map.SerializationConfig.isEnabled.
Now we (again) explicitly define that jira-testkit-client depends on jackson 1.9.1 to resolve this problem.